### ISSUE TITLE
Exception in AssetCatalog when searching for csv resources

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2135]
If, having run the building-a-data-catalog notebook I try and search for the file `file://secured/research/clinical-trials/drop-foot/DropFootMeasurementsWeek1.csv` using it's fully qualified name (as written) in the Asset Search UI I get exceptions including:
```
2019-11-29 14:57:25.898 ERROR 33714 --- [nio-8443-exec-4] o.o.o.u.u.s.s.AssetCatalogOMASService    : Error searching the assets by criteria file://secured/research/clinical-trials/drop-foot/DropFootMeasurementsWeek1.csv
2019-11-29 14:57:25.920  WARN 33714 --- [nio-8443-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController#handleAssetCatalogException(AssetCatalogException, WebRequest)

java.lang.IllegalStateException: Could not resolve parameter [0] in protected org.springframework.http.ResponseEntity<java.lang.Object> org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController.handleAssetCatalogException(org.odpi.openmetadata.accessservices.assetcatalog.exception.AssetCatalogException,org.springframework.web.context.request.WebRequest): No suitable resolver
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:164) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:403) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
```
It appears the UI passes the search string through to asset-catalog as is but an exception occurs.

If a simpler search string like 'csv' is entered, I do get assets returned, but '1.csv' fails. This may relate to the use of regex vs the user expectation of a search box.

Note also that with csv results found, whilst any result can be clicked,  the user is taken just to the lineage screen [though this is more a design/work in progress issue], with the expectation of this being a relational resource?

For ref: image of searching for csv : https://pasteboard.co/IIWFV8O.png cc: @davidradl

**Comment by danielaotelea** [comment]
Hi,

This PR: https://github.com/odpi/egeria/pull/2140 should fix the issue described here.

**Comment by planetf1** [comment]
Unfortunately @danielaotelea I tried building with the PR above, 
```
2019-12-10 12:20:25.248 ERROR 52317 --- [nio-8443-exec-7] o.o.o.u.u.s.s.AssetCatalogOMASService    : Error searching the assets by criteria file://secured/research/clinical-trials/drop-foot
2019-12-10 12:20:25.264  WARN 52317 --- [nio-8443-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController#handleAssetCatalogException(AssetCatalogException, WebRequest)

java.lang.IllegalStateException: Could not resolve parameter [0] in protected org.springframework.http.ResponseEntity<java.lang.Object> org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController.handleAssetCatalogException(org.odpi.openmetadata.accessservices.assetcatalog.exception.AssetCatalogException,org.springframework.web.context.request.WebRequest): No suitable resolver
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:164) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:403) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:141) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1300) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1111) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
```
......
```
2019-12-10 12:20:25.280 ERROR 52317 --- [nio-8443-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is PropertyServerException{reportedHTTPCode=503, reportingClassName='org.odpi.openmetadata.accessservices.assetcatalog.AssetCatalog', reportingActionDescription='searchByType', errorMessage='OMAG-COMMON-503-001 A client-side exception was received from API call searchByType to OMAG Server cocoMDS2 at http://localhost:8080.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpClientErrorException$BadRequest was received by method searchByType from API call http://localhost:8080/servers/{0}/open-metadata/access-services/asset-catalog/users/{1}/search/{2} to server cocoMDS2 on platform http://localhost:8080.  The error message was 400 Bad Request', reportedSystemAction='The server has issued a call to the open metadata access service REST API in a remote server and has received an exception from the local client libraries.', reportedUserAction='Look for errors in the local server's console to understand and correct the source of the error.', reportedCaughtException=RESTServerException{reportedHTTPCode=503, reportingClassName='org.odpi.openmetadata.adapters.connectors.restclients.spring.SpringRESTClientConnector', reportingActionDescription='searchByType', errorMessage='CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpClientErrorException$BadRequest was received by method searchByType from API call http://localhost:8080/servers/{0}/open-metadata/access-services/asset-catalog/users/{1}/search/{2} to server cocoMDS2 on platform http://localhost:8080.  The error message was 400 Bad Request', reportedSystemAction='The client has issued a call to the open metadata access service REST API in a remote server and has received an exception from the local client libraries.', reportedUserAction='Review the error message to determine the cause of the error.  Check that the server is running an the URL is correct. Look for errors in the local server's console to understand and correct the cause of the error. Then rerun the request', reportedCaughtException=org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request}, relatedProperties=null}] with root cause

org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:79) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:123) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
```

I basically run the configure, start, asset management/building a data catalog notebooks, and then did a query in the UI for 'file://secured/research/clinical-trials/drop-foot'

**Comment by danielaotelea** [comment]
Hi, Nigel! Also, for UI is a opened PR: https://github.com/odpi/egeria/pull/2132

**Comment by planetf1** [comment]
Thanks. I've tested with both PRs.

It definately works better - for example I can just search for 'dropfoot' and get some results.

However if I do a search for 'file://secured/research/clinical-trials/drop-foot/DropFootMeasurementsWeek3.csv' I still get an exception pretty much as above

cc: @danielaotelea

**Comment by planetf1** [comment]
ie
```
2019-12-12 10:41:02.898 ERROR 68732 --- [nio-8443-exec-2] o.o.o.u.u.s.s.AssetCatalogOMASService    : Error searching the assets by criteria file://secured/research/clinical-trials/drop-foot/DropFootMeasurementsWeek3.csv
2019-12-12 10:41:02.899  WARN 68732 --- [nio-8443-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController#handleAssetCatalogException(AssetCatalogException, WebRequest)

java.lang.IllegalStateException: Could not resolve parameter [0] in protected org.springframework.http.ResponseEntity<java.lang.Object> org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController.handleAssetCatalogException(org.odpi.openmetadata.accessservices.assetcatalog.exception.AssetCatalogException,org.springframework.web.context.request.WebRequest): No suitable resolver
```

**Comment by danielaotelea** [comment]
Hi, Nigel! I have a fix for this issue in the PR #2228

**Comment by planetf1** [comment]
thanks. the crashing issue is indeed now fixed. Closing
