### ISSUE TITLE
Something's not quite right on the newly-deployed site?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#587]
Looks like something hasn't quite gone right on the newly-deployed site.  The "Home" page is particularly disconcerting, as it looks blank (actually if you scroll down far enough the content is still there, but it isn't obvious):

<img width="1280" alt="screenshot 2019-01-22 at 00 13 37" src="https://user-images.githubusercontent.com/5864283/51504795-c6638e00-1dda-11e9-93ea-99fba66cf6ad.png">

Other pages, however, seem to adopt the new style (not sure about the white border along the left bar, though?):

<img width="1280" alt="screenshot 2019-01-22 at 00 14 23" src="https://user-images.githubusercontent.com/5864283/51504826-dbd8b800-1dda-11e9-96c8-91da2a272136.png">

While most pages, generally, seem to have lost all theming:

<img width="1280" alt="screenshot 2019-01-22 at 00 15 58" src="https://user-images.githubusercontent.com/5864283/51504842-f14de200-1dda-11e9-870c-b2f6302137b2.png">

@alexcontini ^^

**Comment by alexcontini** [comment]
@cmgrote I see the issue and this should solve it - for some reason when live the default.html and homepage.html layouts aren't reading the css properly. It's because the css links at the top of both layout files says this:

<link rel="stylesheet" type="text/css" media="screen" href="{{ '/assets/css/style.css?v=' | append: site.github.build_revision | relative_url }}"> which worked on the test site but seems that if it is changed to 
<link rel="stylesheet" type="text/css" media="screen" href="{{ '/assets/css/style.**s**css?v=' | append: site.github.build_revision | relative_url }}"> (replacing .css with .scss)

it will work. I am creating a new PR now with the fixes and will tag you!

**Comment by alexcontini** [comment]
new PR to fix is here: https://github.com/odpi/egeria/pull/588

**Comment by cmgrote** [comment]
Looking much better -- but still some minor issues:

- The Egeria logo on the upper-left of most pages doesn't seem to render
- Pages with larger diagrams end up with truncated (rather than scaled or horizontally-scrollable) images
- I'm wondering if the links along the left side should be spaced one per line as well (?)
- Each page also seems to have a vast amount of empty whitespace at the bottom (more than an entire page's worth)

<img width="1280" alt="screenshot 2019-01-22 at 09 09 41" src="https://user-images.githubusercontent.com/5864283/51524278-a0171000-1e25-11e9-99ea-7a7a1b2013be.png">

(Link: https://odpi.github.io/egeria/open-metadata-publication/website/open-metadata-types/)

**Comment by alexcontini** [comment]
@cmgrote here is a PR to fix the issues: https://github.com/odpi/egeria/pull/598

The only one it might not have fixed is the image width on the markdown pages (how the diagrams are not at 100% on some pages) as it seems to change when live, I will check as soon as merged and fix if not fixed!

**Comment by cmgrote** [comment]
Ok, very close now -- only bits I can still see as problematic:

- the images getting truncated still
- the links to Tutorials, Samples, Design, About all link to the same page (and should probably link to other pages...)

Tutorials I would link to this page: https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-tutorials

Samples I would link to this page: https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-samples/README.md

Design I would link to one of these pages:
- https://github.com/odpi/egeria/blob/master/open-metadata-publication/website/README.md#technical-components
- https://github.com/odpi/egeria/blob/master/open-metadata-publication/website/open-metadata-specifications/README.md

About I would link to this page: https://github.com/odpi/egeria/blob/master/open-metadata-publication/website/README.md

**Comment by mandy-chessell** [comment]
I have updated the sidebar links and removed the duplication between index.md and README.md.

**Comment by cmgrote** [comment]
Love the addition of the glossary!
