### ISSUE TITLE
egeria-release-1.0 build fails in kafka connector

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#896]
The egeria release 1.0 branch currently fails to build.
See https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-clm-egeria-release-1.0/

It would appear one of the following is to blame:
odpi/egeria#861 - Limit maximum size of kafka event queue (commit: 1dfa587) (details)
odpi/egeria#860 - Don't log entire list when checking for events in (commit: 7db1564) (details)
odpi/egeria#860 - Address review comments (commit: 4e890d1) (details)
odpi/egeria#861 - Fix issues (commit: 7f3b352) (details)
odpi/egeria#861 - Cleanup (commit: 3f8a566) (details)
odpi/egeria#861 - More cleanup (commit: 9443cc4) (details)

I have built locally & get the same results as jenkins - so I think the build config is correct.

cc: @mandy-chessell

**Comment by jnhagelberg** [comment]
I'll take a look -- looks like this is related to missing license headers

**Comment by jnhagelberg** [comment]
@mandy-chessell @planetf1 This will likely be fixed by one or both of these PRs.  Not sure why they have not been merged yet...

https://github.com/odpi/egeria/pull/877
https://github.com/odpi/egeria/pull/880

**Comment by planetf1** [comment]
I see 880 has been merged just now. However after this I see a RAT error :

```
  /Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumerProperty.java
  /Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumerConfiguration.java
  /Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/apache/kafka/clients/consumer/KafkaConfigurationWrapper.java
```

Unfortunately we don't seem to have the same pre-checks in place on this branch. I'll raise the issue with the LF team as it would help if we had the same checks as we have on master for any designated release branches.

**Comment by planetf1** [comment]
@mandy-chessell I think that as repo admin, you may be able to compare the configuration of master with any 'release' branches. I think they should be the same. If more changes are needed I can check with the LF team (ref: https://help.github.com/en/articles/enabling-required-status-checks )

**Comment by jnhagelberg** [comment]
Interesting.  I just pulled from master, and I'm not seeing that.  I did see 
```
ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (rat-check) on project open-metadata-demos: Too many files with unapproved license: 8 See RAT report in: /Users/jeff/git/jhagelberg-egeria/egeria/open-metadata-resources/open-metadata-demos/target/rat.txt -> [Help 1]
```
which is unexpected, but that is because of the eclipse project in my local environment.  The RAT check for "Kafka Open Metadata Topic Connector" passed for me.

Very strange.

**Comment by planetf1** [comment]
Yes I do still get the error — I checked against upstream currently.

The first file for example begins:

```package org.odpi.openmetadata.adapters.eventbus.topic.kafka;

/**
 * Configurable properties for the KafkaOpenMetadataEventConsumer
 *
 */```

So no license notice.

Going to github itself, the latest file is the same - as can be seen at https://github.com/odpi/egeria/blob/egeria-release-1.0/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumerProperty.java

The last change looks like #861

The last formal build was Apr 6 (it's only scheduled weekly - and as above has no triggers setup)

Github also confirms no commits since Mar 25  - https://github.com/odpi/egeria/commits/egeria-release-1.0 

With all that being said, I can see your pull request was merged at https://github.com/odpi/egeria/pull/880/files - and this does indeed fix the SPDX headers. Yet for some reason I don't see those changes.... The commit was eac796decb645a6d67c11dce03d8ba524a73c95e which I don't see in my log - nor that of the release.

I'm unable to explain the discrepancy

**Comment by planetf1** [comment]
At this point I wonder if it's something to do with branch management/git history... when mandy committed that PR it only had an older commit. Could it be down to the same branch being used for a multiple PRs and with some squashing of commits/rebasing done on that branch (which is a potential problem once anyone else refers to the commits).

I'd be inclined to 
 - save existing tree manually outside git
 - do a manual compare
 -  a hard reset on local/remote branch (from odpi fork)
 - OR create a new branch from master
 - reapply necessary change
 - new PR etc

but you may well know more :-)

**Comment by jnhagelberg** [comment]
@planetf1 I just did a 
```
git clone https://github.com/odpi/egeria
```
in a clean directory followed by
```
mvn install
```

Everything built with no errors.

I am wondering if this is perhaps related to the maven or RAT version being used.

I built the code with maven 3.6.0.  It ended up using apache-rat-plugin:0.12:

```
[INFO] --- apache-rat-plugin:0.12:check (rat-check) @ kafka-open-metadata-topic-connector ---
[INFO] Added 3 additional default licenses.
[INFO] Enabled default license matchers.
[INFO] Added 2 custom approved licenses.
[INFO] Will parse SCM ignores for exclusions...
[INFO] Finished adding exclusions from SCM ignore files.
[INFO] 61 implicit excludes (use -debug for more details).
[INFO] Exclude: /CNAME
[INFO] Exclude: **/banner.txt
[INFO] Exclude: **/*.json
[INFO] Exclude: **/*.patch
[INFO] Exclude: **/*.log
[INFO] Exclude: **/*.csv
[INFO] Exclude: **/*.iml
[INFO] Exclude: **/*.registrystore
[INFO] Exclude: **/*.results
[INFO] Exclude: **/target/**
[INFO] Exclude: **/venv/**
[INFO] Exclude: **/.repository/**
[INFO] Exclude: **/charts/**/charts/**
[INFO] Exclude: **/log
[INFO] Exclude: **/*.lock
[INFO] Exclude: **/m2repo*/**
[INFO] Exclude: **/venv/**
[INFO] Exclude: **/archives/patches/egeria.patch
[INFO] Exclude: **/docs/**/*.xml
[INFO] Exclude: **/docs/**/*.svg
[INFO] Exclude: **/website/**/*.xml
[INFO] Exclude: **/dependency-reduced-pom.xml
[INFO] Exclude: **/.classpath
[INFO] Exclude: **/.project
[INFO] Exclude: **/.settings/**
[INFO] 11 resources included (use -debug for more details)
[INFO] Rat check: Summary over all files. Unapproved: 0, unknown: 0, generated: 0, approved: 10 licenses
```

**Comment by jnhagelberg** [comment]
I am starting to suspect that there is some configuration problem in your local environment, especially if what you see locally does not match what is in github.

**Comment by planetf1** [comment]
i think I've eliminated that possibility.

If you go to github, click on branches/egeria-release-1.0 & then navigate through, you'll get to a file like https://github.com/odpi/egeria/blob/egeria-release-1.0/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumerProperty.java 

where you can see the spdx headers are not present.

furthermore the linux foundation builds are failing
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-clm-egeria-release-1.0/lastBuild/console

Can you perhaps resync with upstream and see what results you get?

**Comment by planetf1** [comment]
note.. this is with egeria-release-1.0 ...
master is ok (which is what you would have built in the transcript above)

**Comment by jnhagelberg** [comment]
@planetf1 Oh, sorry, I thought it was a problem with master.  I now see the problem in egeria-release-1.0.  I've created a new PR: https://github.com/odpi/egeria/pull/908

**Comment by planetf1** [comment]
Thanks.. seen.. checked. all good :-)
